all: clean barco triangulo novo

barco:
	gcc -o barco.o -lglut barco.c

triangulo:
	gcc -o triangulo.o -lglut projetoCG_Fernando.cpp

novo:
	gcc -o pacman.o -lglut pacman.c

clear: clean

clean:
	rm *.o
