all: clean barco triangulo novo

barco:
	gcc -o barco.o -lglut barco.c

triangulo:
	gcc -o triangulo.o -lglut projetoCG_Fernando.cpp

novo:
	gcc -o novo_barco.o -lglut novo_barco.c

clear: clean

clean:
	rm *.o
